name: "workflow run webhook"

on:
  workflow_run:
    workflows: ["on workflow_run"]
    types: 
      - completed
      - requested

jobs:
  job:
    name: Handle workflow_run webhook
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.payload) }}"
